import type { Metadata } from "next";
import SiteFrame from "@/components/SiteFrame";
import CTABanner from "@/components/CTABanner";
import { ArrowUpRight, Landmark } from "lucide-react";
import { SITE } from "@/lib/site";

export const metadata: Metadata = { title: "Conozca sus derechos", description: "Recursos oficiales de educación especial para padres y familias de California.", alternates: { canonical: "/es/recursos", languages: { en: "/know-your-rights", es: "/es/recursos" } } };
const RESOURCES = [
  { title: "Derechos de los padres", source: "Departamento de Educación de California", summary: "Resumen oficial de notificación, consentimiento, evaluaciones, expedientes y opciones para resolver desacuerdos.", href: "https://www.cde.ca.gov/sp/se/pssummary.asp" },
  { title: "Recursos sobre el IEP", source: "Departamento de Educación de California", summary: "Información oficial sobre el desarrollo e implementación del Programa de Educación Individualizado.", href: "https://www.cde.ca.gov/sp/se/iepresources.asp" },
  { title: "Resumen de derechos educativos", source: "Oficina de Audiencias Administrativas de California", summary: "Una descripción de los derechos de educación especial y del proceso debido en California.", href: "https://www.dgs.ca.gov/OAH/Case-Types/Special-Education/Self-Help/Summary-of-Educational-Rights" },
  { title: "Información de IDEA para familias", source: "Departamento de Educación de EE. UU.", summary: "Recursos federales sobre la Ley de Educación para Individuos con Discapacidades.", href: "https://sites.ed.gov/idea/parents-families/" },
] as const;
export default function ResourcesPageEs() { return <SiteFrame locale="es" otherLocaleHref="/know-your-rights"><section className="bg-[color:var(--surface)] py-14 md:py-section-desktop"><div className="container-x"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[color:var(--brand-secondary)] mb-4">Recursos para padres</p><h1 className="font-serif font-bold text-[color:var(--brand-primary)]" style={{ fontSize: "clamp(2rem, 4.4vw, 3.052rem)", lineHeight: 1.15 }}>Conozca sus derechos.</h1><p className="mt-6 max-w-prose text-lg leading-relaxed">Empiece con información publicada por las agencias que administran las leyes estatales y federales de educación especial.</p></div></section><section className="py-12 md:py-20"><div className="container-x"><div className="grid gap-6 md:grid-cols-2">{RESOURCES.map((r) => <article key={r.href} className="card flex h-full flex-col"><div className="mb-4 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.12em] text-[color:var(--brand-secondary)]"><Landmark aria-hidden="true" className="h-4 w-4" />Fuente oficial</div><h2 className="font-serif text-xl font-bold text-[color:var(--brand-primary)]">{r.title}</h2><p className="mt-2 text-sm font-semibold text-[color:var(--text-secondary)]">{r.source}</p><p className="my-4 flex-1 leading-relaxed">{r.summary}</p><a href={r.href} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 font-semibold">Abrir recurso oficial <ArrowUpRight aria-hidden="true" className="h-4 w-4" /><span className="sr-only"> (se abre en una nueva pestaña)</span></a></article>)}</div><p className="mt-10 max-w-prose text-sm text-[color:var(--text-secondary)]">Estos recursos ofrecen información general, no asesoramiento legal. Consulte la página oficial para la versión vigente.</p></div></section><CTABanner heading="¿Necesita ayuda con su situación?" body="La información oficial es un buen comienzo. Contacte al bufete para hablar de los hechos y los próximos pasos posibles." primaryCta={{ label: "Contacte al bufete", href: "/es/contacto" }} secondaryCallLabel={`Llame al ${SITE.phone}`} /></SiteFrame>; }
